language: node_js
node_js:
  - '14'
  - '12'
  - '10'
before_script: npm run lint
after_success: npm run coveralls
dependencies:
  post:
    - npm run bootstrap

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kempdogg@gmail.com
